CREATE DATABASE IF NOT EXISTS ITSCARD
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `usuario` (
`id` INT NOT NULL AUTO_INCREMENT,
`usuario` VARCHAR(70) NOT NULL,
PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `cards` (
`id` INT NOT NULL AUTO_INCREMENT,
`autor` INT NOT NULL,
`tipo` VARCHAR(40) NOT NULL,
`data` timestamp NOT NULL,
`titulo` VARCHAR(100) NOT NULL,
`postagem` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`));

